In [1]:
import numpy as np

# Define the Softmax activation function
def softmax(x):
    exp_x = np.exp(x - np.max(x)) # subtracting max for numerical stability
    return exp_x / exp_x.sum(axis=0)

# 1. Initialize matrices and input vectors based on the slide's example
W_h = np.array([
    [0.5, 0.9, 0.3],
    [0.3, 0.2, 0.1],
    [0.9, 0.8, 0.2]
])

h_0 = np.array([
    [0],
    [0],
    [0]
])

W_x = np.array([
    [0.6, 0.8, 0.8, 0.8],
    [0.2, 0.8, 0.7, 0.9],
    [0.9, 0.8, 0.1, 0.2]
])

X_1 = np.array([
    [1],
    [0],
    [0],
    [0]
])

W_y = np.array([
    [0.9, 0.8, 0.3],
    [0.2, 0.3, 0.4],
    [0.6, 0.9, 0.1],
    [0.5, 0.0, 0.3]
])

# 2. Compute hidden nodes calculation (a_1)
# Formula: a_t = W_H * h_{t-1} + W_X * X_t
a_1 = np.dot(W_h, h_0) + np.dot(W_x, X_1)
print("a_1 (Hidden Nodes):\n", a_1)
print("-" * 30)

# 3. Apply activation function (tanh) to get new hidden state (h_1)
# Formula: h_t = tanh(a_t)
h_1 = np.tanh(a_1)
print("h_1 (New Hidden State):\n", np.round(h_1, 2))
print("-" * 30)

# 4. Compute output prediction (y_1) using Softmax
# Formula: y_t = softmax(W_Y * h_t)
raw_y1 = np.dot(W_y, h_1)
y_1 = softmax(raw_y1)
print("y_1 (Predicted Probabilities):\n", np.round(y_1, 2))

a_1 (Hidden Nodes):
 [[0.6]
 [0.2]
 [0.9]]
------------------------------
h_1 (New Hidden State):
 [[0.54]
 [0.2 ]
 [0.72]]
------------------------------
y_1 (Predicted Probabilities):
 [[0.32]
 [0.21]
 [0.24]
 [0.22]]
