In [5]:
import numpy as np

# Example sentence tokens
tokens = ["What", "are", "the", "symptoms", "of", "diabetes", "?"]

# Step 1: Create random embeddings (for demo)
np.random.seed(42)
d_model = 8  # embedding size
embeddings = np.random.rand(len(tokens), d_model)

# Step 2: Initialize weight matrices
W_Q = np.random.rand(d_model, d_model)
W_K = np.random.rand(d_model, d_model)
W_V = np.random.rand(d_model, d_model)

# Step 3: Compute Q, K, V
Q = embeddings @ W_Q
K = embeddings @ W_K
V = embeddings @ W_V

# Step 4: Compute attention scores
scores = Q @ K.T

# Step 5: Scale scores
d_k = K.shape[-1]
scaled_scores = scores / np.sqrt(d_k)

# Step 6: Softmax function
def softmax(x):
    exp_x = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return exp_x / np.sum(exp_x, axis=-1, keepdims=True)

attention_weights = softmax(scaled_scores)

# Step 7: Compute final output
output = attention_weights @ V

# Print results
print("Attention Weights:\n", attention_weights)
print("\nSelf-Attention Output:\n", output)

Attention Weights:
 [[0.005 0.001 0.    0.001 0.008 0.    0.984]
 [0.01  0.003 0.001 0.001 0.013 0.001 0.971]
 [0.019 0.008 0.003 0.004 0.027 0.003 0.936]
 [0.015 0.006 0.002 0.003 0.021 0.002 0.952]
 [0.004 0.001 0.    0.    0.006 0.    0.989]
 [0.015 0.006 0.002 0.003 0.017 0.002 0.956]
 [0.001 0.    0.    0.    0.001 0.    0.998]]

Self-Attention Output:
 [[2.682 2.764 3.507 3.678 3.1   2.44  2.439 3.24 ]
 [2.674 2.752 3.486 3.66  3.087 2.432 2.433 3.228]
 [2.655 2.721 3.431 3.615 3.053 2.409 2.418 3.194]
 [2.664 2.735 3.456 3.635 3.068 2.419 2.425 3.209]
 [2.684 2.768 3.515 3.685 3.105 2.443 2.441 3.244]
 [2.665 2.739 3.464 3.64  3.072 2.422 2.426 3.213]
 [2.688 2.776 3.53  3.696 3.114 2.449 2.445 3.253]]
